### ISSUE TITLE
Does not work with latest Vaadin 8 version due use of old Jsoup API

### ISSUE THREAD

**Issue by TatuLund** [Legioth/splash-screen#9]
https://github.com/Legioth/splash-screen/blob/master/splashscreen/src/main/java/org/vaadin/leif/splashscreen/SplashScreenHandler.java#L18

See exception

11:28:41.625 [qtp1989092248-126] ERROR c.vaadin.server.DefaultErrorHandler - 
java.lang.NoSuchMethodError: org.jsoup.nodes.DataNode.<init>(Ljava/lang/String;Ljava/lang/String;)V
	at org.vaadin.leif.splashscreen.SplashScreenHandler.modifyBootstrapPage(SplashScreenHandler.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:699)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:392)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:356)
	at com.vaadin.server.VaadinSession.modifyBootstrapResponse(VaadinSession.java:878)
	at com.vaadin.server.BootstrapHandler.getBootstrapHtml(BootstrapHandler.java:453)
	at com.vaadin.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:421)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:33)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1659)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:457)

**Comment by jringbox** [comment]
@Legioth Any chances of fixing this?

**Comment by Legioth** [comment]
I haven't touched this project in 6 years. I guess there isn't any fundamental reason for why it wouldn't work if someone would take the time to change the code to use newer APIs. Please submit a PR if you find something that works.
